DELETE FROM STUDENT WHERE GROUPNUMBER >= 4;
DELETE FROM STUDENT WHERE ID IN (SELECT DISTINCT student_id FROM Mark WHERE mark < 4);
DELETE FROM PaymentType WHERE name = 'DAILY';
DELETE FROM Mark WHERE mark < 7;