SELECT * FROM MARK WHERE MARK>6 ORDER BY MARK DESC;
SELECT * FROM PAYMENT WHERE AMOUNT>300 ORDER BY AMOUNT;
SELECT * FROM PAYMENTTYPE ORDER BY NAME;
SELECT * FROM STUDENT ORDER BY NAME DESC ;
SELECT STUDENT.ID,STUDENT.NAME,STUDENT.BIRTHDAY,STUDENT.GROUPNUMBER FROM STUDENT INNER JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID WHERE PAYMENT.AMOUNT>1000 GROUP BY STUDENT.ID ORDER BY STUDENT.BIRTHDAY;



