ALTER TABLE STUDENT ALTER COLUMN BIRTHDAY DATE NOT NULL ;
ALTER TABLE MARK ADD CONSTRAINT CHK_MARK CHECK (MARK >= 1 and MARK<=10 AND STUDENT_ID IS NOT NULL AND SUBJECT_ID IS NOT NULL );
ALTER TABLE SUBJECT ADD CONSTRAINT CHK_SUBJECT CHECK (GRADE BETWEEN 1 AND 5);
ALTER TABLE PAYMENTTYPE ALTER COLUMN NAME VARCHAR UNIQUE ;
ALTER TABLE PAYMENT ADD CONSTRAINT CHK_PAYMENT CHECK (TYPE_ID IS NOT NULL AND AMOUNT IS NOT NULL AND PAYMENT_DATE IS NOT NULL);
