SELECT BIRTHDAY FROM STUDENT ORDER BY BIRTHDAY DESC LIMIT 1;
SELECT PAYMENT_DATE FROM PAYMENT ORDER BY PAYMENT_DATE  LIMIT 1;
SELECT AVG(MARK.MARK) FROM MARK INNER JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE SUBJECT.NAME LIKE 'Math';
SELECT MIN(PAYMENT.AMOUNT) FROM PAYMENT INNER JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME='WEEKLY';
