SELECT * FROM STUDENT WHERE BIRTHDAY = (SELECT MAX(STUDENT.BIRTHDAY) from student);
SELECT * FROM PAYMENT WHERE PAYMENT_DATE = (SELECT MIN(PAYMENT_DATE) FROM PAYMENT);
SELECT AVG(SUBJECT.GRADE) FROM SUBJECT WHERE NAME ='Math';
SELECT MIN(PAYMENT.AMOUNT) FROM PAYMENT INNER JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME='WEEKLY';
