SELECT STUDENT.ID,STUDENT.NAME, STUDENT.BIRTHDAY,STUDENT.GROUPNUMBER FROM STUDENT INNER JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID GROUP BY STUDENT.ID, STUDENT.NAME, STUDENT.BIRTHDAY, STUDENT.GROUPNUMBER HAVING AVG(MARK.MARK)>8;
SELECT STUDENT.ID,STUDENT.NAME FROM STUDENT INNER JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID GROUP BY STUDENT.ID, STUDENT.NAME HAVING MIN(MARK.MARK)>7;
SELECT STUDENT.ID,STUDENT.NAME FROM STUDENT INNER JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID WHERE PAYMENT_DATE=2019 GROUP BY STUDENT.ID, STUDENT.NAME HAVING COUNT(STUDENT_ID)>2;
