UPDATE SUBJECT SET GRADE=5 WHERE NAME='End of Suburbia: Oil Depletion and the Collapse of the American Dream';
UPDATE STUDENT SET GROUPNUMBER=8 WHERE NAME ='Tremaine Worvill';
UPDATE PAYMENT SET AMOUNT=500 AND STUDENT_ID=2 WHERE TYPE_ID=2 AND PAYMENT_DATE > '2021-01-01';
UPDATE MARK SET MARK=2  WHERE SUBJECT_ID=315 ;